import React from 'react';
import { RNG } from './utils/rng';

export type Difficulty = 1 | 2 | 3;

export type AppMode = 'single' | 'variant' | 'set';

export const MODE_LABELS: Record<AppMode, string> = {
  single: 'Тренажёр',
  variant: 'Вариант',
  set: 'Набор',
};

export const DIFFICULTY_LABELS: Record<Difficulty, string> = {
  1: 'Легче ОГЭ',
  2: 'Как на ОГЭ',
  3: 'Сложнее ОГЭ'
};

export interface TaskInstance {
  id: string;               // Unique id for current session
  taskId: number;           // 1 to 16
  difficulty: Difficulty;
  taskData: any;            // Custom structure generated by task module
}

export interface TaskModuleState {
  userAnswer: string;
  setUserAnswer: (val: string) => void;
  isSubmitted: boolean;
  showHints: boolean;
  isCorrect?: boolean;
}

export interface TaskModule {
  id: number;
  title: string;
  description: string;
  topics: string[];   // темы задания для конструктора набора
  maxPoints: number;  // максимальный балл
  /**
   * Generates task data.
   * @param difficulty Difficulty level (1, 2, or 3)
   * @param rng Deterministic random number generator
   */
  generate: (difficulty: Difficulty, rng: RNG) => any;
  /**
   * Renders the generated task's statement, inputs, and hints.
   */
  render: (
    taskData: any,
    state: TaskModuleState
  ) => React.ReactNode;
  /**
   * Standardized checker.
   * Compares the userAnswer against correct solution.
   */
  check: (taskData: any, userAnswer: string) => boolean;
  /**
   * Detailed score checker returning score and maxScore.
   */
  checkScore?: (taskData: any, userAnswer: string) => { score: number; maxScore: number };
}
